
services:
  - docker
language: cpp
env:
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO="ros"  UPSTREAM_WORKSPACE=https://github.com/fkie/iop_core/blob/master/jaus_core.rosinstall
    - ROS_DISTRO="jade" ROS_REPO="ros"   UPSTREAM_WORKSPACE=https://github.com/fkie/iop_core/blob/master/jaus_core.rosinstall
    - ROS_DISTRO="kinetic" ROS_REPO="ros-shadow-fixed"  UPSTREAM_WORKSPACE=https://github.com/fkie/iop_core/blob/master/jaus_core.rosinstall
    - ROS_DISTRO="kinetic" ROS_REPO="ros"  UPSTREAM_WORKSPACE=https://github.com/fkie/iop_core/blob/master/jaus_core.rosinstall
    - ROS_DISTRO="lunar" ROS_REPO="ros"  UPSTREAM_WORKSPACE=https://github.com/fkie/iop_core/blob/master/jaus_core.rosinstall
install:
  - sudo apt-get install default-jdk -y
  - sudo apt-get install scons ant -y
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
