
services:
  - docker
language: cpp
env:
  global:
    - CATKIN_CONFIG='--no-install'
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO="ros"  UPSTREAM_WORKSPACE=file  $ROSINSTALL_FILENAME=".travis.rosinstall"
    - ROS_DISTRO="jade" ROS_REPO="ros"   UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="kinetic" ROS_REPO="ros-shadow-fixed"  UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="kinetic" ROS_REPO="ros"  UPSTREAM_WORKSPACE=file
    - ROS_DISTRO="lunar" ROS_REPO="ros"  UPSTREAM_WORKSPACE=file
install:
  - sudo apt-get install default-jdk -y
  - sudo apt-get install scons ant -y
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
after_script:
  - cat /root/catkin_ws/build/jaustoolset/get_jts_source.stderr
script:
  - .ci_config/travis.sh
